### ISSUE TITLE
Normal AI is not working at all on Fedora 28

### ISSUE THREAD

**Issue by fusion809** [drogoganor/DarkReign#20]
Hi,

While the game starts fine on Linux now the normal AI does absolutely nothing, just leaves the construction rig to stand there. I was playing against five normal AIs and they were all just standing there.

My logs (of the exception logs only the last one pertains to this issue) are here: [logs.zip](https://github.com/drogoganor/DarkReign/files/2479163/logs.zip). You'll find evidence in it of the next bug I'm about to report too, as at the end of a game the game crashed. 

Thanks for your time,
Brenton

**Comment by drogoganor** [comment]
Hi,

Yes I'm afraid the skirmish AI is broken at the moment, due to the recent introduction of code to make the construction rigs build like the original game. I'm still yet to look at solving it but it's likely to take a while. I'll make a note on the main page that advises people that the skirmish AI is broken so as not to disappoint people.

Thanks for the detailed report and logs.

**Comment by drogoganor** [comment]
This should be solved as of latest.

**Comment by fusion809** [comment]
Yep it is, closing.
