### ISSUE TITLE
Commit 237 (c2f0c2d), but not 236 crashes on start up on Arch Linux: Cannot locate type: TerrainRendererInfo

### ISSUE THREAD

**Issue by fusion809** [drogoganor/DarkReign#22]
Hi,

Sadly commit 237 crashes, on start up on Arch Linux with [this exception log](https://gist.github.com/3c2fea3d32e4ede9317ef2ae9bdb2d3e). The most important lines are probably:

```bash
Loading mod: dr
Exception of type `System.AggregateException`: One or more errors occurred.
Inner
  Exception of type `System.InvalidOperationException`: Cannot locate type: TerrainRendererInfo
    at OpenRA.ObjectCreator+<>c.<.cctor>b__20_0 (System.String s) [0x00015] in <f7e8b215d0d54cb597299ec7f4b505f5>:0 
  at OpenRA.ObjectCreator.CreateObject[T] (System.String className, System.Collections.Generic.Dictionary`2[TKey,TValue] args) [0x0001a] in <f7e8b215d0d54cb597299ec7f4b505f5>:0 
  at OpenRA.ObjectCreator.CreateObject[T] (System.String className) [0x00008] in <f7e8b215d0d54cb597299ec7f4b505f5>:0 
```

The only other log written to during this error was perf.log, which can be found [here](https://gist.github.com/3ad9ce301008e3d8fc1c8534ddfa012a).

If there's any other pieces of information you need to diagnose and fix this problem simply ask.

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
I receive this same error on Solus with commit number 237.

**Comment by drogoganor** [comment]
Thanks for the report. This is probably due to my recent updates from bleed which requires this new TerrainRenderer. I'm pretty sure I didn't do a push to my OpenRA fork in a timely manner and you have the previous engine version. Sorry about that. On Windows, when compiling from source, I delete the "engine" directory and do another make all which will fetch the (now) correct OpenRA version and compile it. This isn't exactly recommended procedure but it will work. Cheers.

**Comment by fusion809** [comment]
Whenever I build a new commit I run `make clean`, which deletes the engine directory anyway. Well this error seems to be gone, sadly it's just exposed another error lol.
