### ISSUE TITLE
AICash trait is unneeded.

### ISSUE THREAD

**Issue by GraionDilach** [drogoganor/DarkReign#32]
A CashTricker trait conditioned to rely on the AI condition on the Player actor should be able to do the job.

**Comment by drogoganor** [comment]
The AICash trait is actually configured to give the AI a lump sum upon game start only. This is because the AI actually pays for their buildings twice, due to the way the SelfConstructing buildings work. The AI can't just place a SelfConstructing building like the player can - they have to produce it through a (near-instant) production queue.

So, we give the AI an extra 20k upon start to compensate for this double payment:

`
AICash: 
	Amount: 20000
	TickEach: 10
	UntilTick: 11
`

**Comment by drogoganor** [comment]
Replaced with CashTrickler. Closing
